version: "3.3"
networks:
    laravel:

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports: 
      - "8081:8000"
    volumes: 
      - "./:/var/www/html"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports: 
      - "3306:3306"
    volumes: 
      - "./mysql:/var/lib/mysql"
    tty: true
    environment:
      DB_DATABASE: za3touri
      DB_USERNAME: user
      DB_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports: 
      - "80:80"
    volumes:
      - "./:/var/www/html" 
    networks:
      - laravel

