version: "3.3"
networks:
  laravel:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports: 
      - "8081:8000"
    volumes: 
      - "./:/var/www/html"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - laravel
  mysql:
    image: mysql:8
    container_name: laravel_mysql
    restart: unless-stoppe
    ports: 
      - "3306:3306"
    volumes: 
      - dbdata:/var/lib/mysql/
      - ./docker/mysql.cnf:/etc/mysql/my.cnf
      - "./mysql:/var/lib/mysql"
    tty: true
    environment:
      MYSQL_DATABASE: za3touri
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports: 
      - "80:80"
    volumes:
      - "./docker/php.sh:/var/www/html" 
    networks:
      - laravel

